### ISSUE TITLE
only 6 game code ?

### ISSUE THREAD

**Issue by herlambang333** [Element21/Quizizz-Hack#1]
first, thanks so much for your code. can you add that? ex ( 613 214 ), https://drive.google.com/file/d/1me8AbcwXa05PjReQkDZPKkgkqU_VdBFB/view?usp=sharing .i hope you can try merge from this code to your code, your code more stable than what i got

**Comment by Element21** [comment]
Thanks for the suggestion and the code! I'm currently working on v2 of the bot. The new version will support game codes and the single-player practice/join links.

**Comment by Element21** [comment]
Right now you can bypass this by joining the game with the code, but on the start game screen, use that link
